#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/opggpost_database?serverTimezone=Asia/Seoul
#    username: admin
#    password: 12345678

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:8080
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true